src/Command.zig
src/Config.zig
src/Output.zig
src/command/layout.zig

This PR adds multiple layouts to river.
State:

Add multiple layouts and a commands to switch the current layout

---

src/Output.zig

This fixes two bugs: First, the height of the slave stack was to high
when using the TopMaster or BottomMaster layouts with no views in the
master stack. Second, the view padding was not respected when using the
Full layout.

Fix layout bugs

---

doc/river.1
doc/riverctl.1

These man pages are hand-written and spellchecked with `hunspell -n`. I did my best to follow the standards of man-pages(7).
`build.zig` should be modified to gzip these files and copy them to `$PREFIX/share/man/man1`.

Add man pages

---

doc/riverctl.1
river/Config.zig
river/Control.zig
river/Rgb.zig
river/command.zig
river/command/set_option.zig
river/render.zig

Implements #43. Hex code is required to be enclosed in double quotes.
```
riverctl set-option border_focused_color "#a1a1a1"
```

command: Added border_focused_color and border_unfocused_color options

---

build.zig
contrib/random-correct-layout.sh
contrib/random-incorrect-layout.sh
doc/river-layouts.1.scd
doc/riverctl.1.scd
river/Output.zig
river/command/layout.zig

This is not even remotely finished yet, but I'll park it here anyway so I have a place to brain-dump.
Progress:
The biggest hurdle by far is definitely the zig standard library not being documented.
A big problem for users will be, that river will halt while the layout executable is running. This is fine for now, but before version 1.0 it should probably be made async somehow, so that a faulty layout executable does not block the entire system, requiring a restart or Sysrq magic. Or instead of async, just abort after an arbitrary amount of time (like 1 second) and fall back to `layoutFull()`.

[WIP] External layouts

---

.gitignore
build.zig
doc/river-layouts.7.scd
doc/river.1.scd
doc/riverctl.1.scd

- Previous hard-coded settings can be now be changes with riverctl or
via environment variables
- Update "See also"
- Rename `river-layouts.1` to `river-layouts.7`

Small man pages fixes and updates

---

contrib/config.sh

You should also consider renaming the full layout to _monocle_ or _single_ to match the new default mapping.

docs: Fix duplicate mapping in config.sh

---

river/Cursor.zig
river/Keyboard.zig
river/Seat.zig
river/c.zig

As discussed in IRC.
This is supposed to work similar to dwm: Trying to move a window will float it. I ended up implementing cursor warp, because it actually simplifies things a bit; I can remove it later though if desired..
TODO:
As it is now, this PR contains some C-like stuff I have to zig-ify first before it can be tested.  Also it might be a good idea to investigate whether function pointers instead of switches in cursor event handling code are more efficient.

Implement moving views via cursor

---

river/Config.zig
river/Decoration.zig
river/DecorationManager.zig
river/View.zig
river/XdgToplevel.zig
river/render.zig

As discussed in IRC an hour ago.
This adds a list of app_ids which are  allowed to use client side decorations. These views will not be set to tiled (beware: the views will still be tiled by river and her layouts, this is just a status influencing how applications draw their windows), they are instructed to use client side decorations and they will not get a border drawn by river.
This settles the CSD vs SSD debate by simply doing both, allowing applications of both kinds to look as intended. Beware that the default is still SSD though.
Currently there is no way of adding any app_ids to the list. I will create a follow-up PR implementing a commands for pushing app_ids to the csd_filter list and the float_filter list.
For testing purposes, the app_id "csd" is hardcoded into the list for …

Implement csd_filter list

---

doc/riverctl.1.scd

The `set-option` command got removed but was still present in SYNOPSIS,
which confused me. It is not the first time, we forgot to update it.

doc: shorten riverctl’s synopsis

---

river/Cursor.zig
river/Root.zig
river/Seat.zig
river/View.zig
river/VoidView.zig
river/XdgToplevel.zig
river/XwaylandView.zig
river/render.zig

- Double buffering focus state ensures that border color is kept in sync
with the transaction state of views in the layout.
- Using a counter instead of a bool will allow for proper handling of
multiple seats. This is done in the same commit to avoid more churn in
the future.

view: double buffer focus, use counter not bool

---

river/Output.zig

~~Currently, river allows resizing views to 0x0, with mouse and via layout. To small sizes may cause severe issues in some applications and a size of 0x0 is a protocol error. Some views, such as GTK ones, set constraints, however this is only an optional feature of the XDG-Shell. To prevent too small views, this PR enforces a minimal view size of 50x50 for both layouts and mouse resizing. This is a totally arbitrary number, low enough to not get in the way of the user but high enough to not cause issues in applications.~~
~~Additionally,~~ this PR fixes a crashing bug which is encountered when a layout defines a width or height smaller than `delta_size`.

Fix bug causing river to crash when layouts define a too small view size

---

river/Cursor.zig
river/InputManager.zig
river/LayerSurface.zig
river/Output.zig
river/Root.zig
river/Seat.zig
river/View.zig
river/VoidView.zig
river/XdgToplevel.zig
river/XwaylandView.zig
river/command/config.zig
river/command/focus_view.zig
river/command/mod_master_count.zig
river/command/mod_master_factor.zig
river/command/send_to_output.zig
river/command/tags.zig
river/command/toggle_float.zig
river/command/toggle_fullscreen.zig
river/command/zoom.zig

- require the caller to use Root.startTransaction() directly
- introduce View.applyPending() to unify logic
- introduce View.shouldTrackConfigure() to unify more logic
- update all callsites to intelligently rearrange only what is necessary

root: refactor transaction initiation

---

doc/riverctl.1.scd
river/Config.zig
river/Cursor.zig
river/command.zig
river/command/focus_follows_cursor.zig

This PR implements the `focus-follows-cursor` command as described in the man page.
In https://github.com/ifreund/river/commit/e05b22ba443e86dd3255e98f559f62c8b4b94f6c the `surfaceAt`, `layerSurfaceAt` etc. functions are moved to output because it seemed more reasonable to have them there.
~I think it works. I've also tested with layer surfaces. The behavior seems strange but I think it is desired. Analogous to this line you cant change the focus with keybindings when the cursor is over a layer surface.~
https://github.com/ifreund/river/blob/976a3ce73d3f83c94576e1220bebbaf79cc8c0e5/river/Seat.zig#L101-L102
~The last thing remaining is that the border is not updated when the focus is changed. I need help with this one.
Looking at https://github.com/ifreund/river/blob/master/river/command/fo …

Focus follows cursor

---

doc/riverctl.1.scd
river/Keyboard.zig
river/Mapping.zig
river/Seat.zig
river/command/map.zig

This implements `-release` from #98.
It also paves the way to implement more optional arguments for map which I plan doing.
~One controversial thing might be moving up the allocation of `Mapping` in `map.zig`. I think it is acceptable because it will only occur when a duplicate mapping would be assigned and this should not happen often. The benefit is the `isEqual` function in `Mapping` which IMO improves readablity.~
To test you can use:
```
riverctl map normal Mod4 F toggle-fullscreen
riverctl map -release normal Mod4 F toggle-fullscreen
```

Implement map -release

---

contrib/config.sh
doc/riverctl.1.scd
river/Config.zig
river/Root.zig
river/Seat.zig
river/View.zig
river/XdgToplevel.zig
river/command.zig
river/command/opacity.zig
river/render.zig

As the title states, this does what #107 does, but with timers. The way it is implemented also gives us a "fade in" effect on view map for free by setting the initial opacity to `0.0` (obviously configurable).
I'll clean up the commits after the review.
---
For the animation I decided to use step-size instead of step-amount. This way the "speed" of the animation is constant instead of the time, which Feels Nicer™,  and is considerably easier to implement, especially w.r.t. changing the target opacity mid-animation. Also, looking at other project, this method of implementing fade effects appears to be more common.

#107, but with timers and double buffering

---

contrib/config.sh
doc/riverctl.1.scd
river/Cursor.zig
river/Output.zig
river/command.zig
river/command/move.zig

This PR introduces ~~two~~ *three* simple commands to move and resize views via the keyboard.
* `move {up,down,left,right} <delta>` to move a view by `delta` in the specified direction.
* `snap {up,down,left,right}` to snap a view to the specified screen edge.
* `resize {horizontal,vertical} <delta>` to resize a view by `delta` in the specified orientation.
Since all three actions remove the view from the layout, the view will be set to floating.
---
In the default config, moving is `Super+Alt+{h,j,k,l}` and snapping is `Super+Alt+Control+{h,j,k,l}`. Resizing ~~which I'll implement sometime in the future will be~~ *is* `Super+Alt+Shift+{h,j,k,l}`.
Went ahead and implemented resizing as well. Works like it does in sway: The views center remains stationary.
All three operations will not …

Implement moving and resizing views via keyboard

---

river/Seat.zig
river/View.zig

Although per XDG spec we technically could, we do not draw anything interesting to watch behind  fullscreened views. As such, server side transparency makes no sense for these views.
With this PR, fullscreened views always get set to an opacity of 1.0 and once they return to their previous state the correct opacity based on their focus state.

Always set fullscreen views to fully opaque

---

river/View.zig

Currently,  if a floating view is moved via the mouse, then enters fullscreen, then leaves fullscreen, it returns to its original, pre-move, position/dimensions. This fixes that.

Bugfix: Update view.float_box when setting a floating view to fullscreen

---

river/Cursor.zig
river/XdgToplevel.zig

Pretty simple patch, since the code that does the actual work is already there, it just needs to be called. Using `Cursor.Mode` is a bit awkward though, since its `self` wants a `Cursor`.

Implement XDG Toplevel move and resize requests.

---

doc/riverctl.1.scd
river/Keyboard.zig
river/command/map.zig

**First patch:** This adds the possibility to use the modifier string "None" (evals to 0) to create mappings without modifiers. This is simply more user friendly then the current way of doing this.
---
**Second patch:** This removes the map checking for translated keysyms. I am pretty sure the raw keysyms cover every possible mapping, so it's simply not necessary.

Some mapping things.

---

contrib/config.sh

The example config now additionally demonstrates how to use a shell loop
to create a mapping in multiple modes, how mediakeys can be mapped and
how to use the "None" modifier.
---
As discussed in #128

Add mediakey maps for locked and normal mode to example config

---

include/bindings.c
include/bindings.h
river/Keyboard.zig
river/Output.zig
river/Root.zig
river/Server.zig
river/c.zig

While working on implementing the virtual pointer protocol, I noticed that most of the hack is not needed.
The problem is the `wlr/render/wlr_renderer.h`.
None of  `wlr/backend.h`, `wlr/backend/noop.h` and `wlr/backend/multi.h` include `wlr/render/wlr_renderer.h` so it should be safe to `@cInclude` them and remove the wrapper functions.

Remove most of the hack which works around @cImport and flexible arrays

---

build.zig
protocol/wlr-output-power-management-unstable-v1.xml
river/Output.zig
river/Server.zig
river/c.zig
river/render.zig

This is my first protocol implementation of any kind.
I need help with one little thing which is that when disabling and enabling afterwards I get an error.
Can you point me to anything I should investigate?
```
info: (server) initializing
debug: (server) new output eDP-1
debug: (server) new output DP-1
info: (server) running...
debug: (server) new xdg_toplevel
debug: (server) view 'Alacritty' mapped
debug: (transaction) started transaction with 1 pending configure(s)
debug: (server) Disabling dmps for output eDP-1
00:00:08.531 [ERROR] [types/wlr_output.c:567] Basic output test failed
debug: (server) Enabling dmps for output eDP-1
info: (server) shutting down
debug: (server) output 'eDP-1' destroyed
debug: (server) output 'DP-1' destroyed
```
For reference here is sways code: …

Implement wlr-output-power-management-unstable-v1 protocol

---

river/Output.zig
river/Root.zig

This is needed for my upcoming PR to implement `wlr_output_management_unstable_v1` (Which should be opened tomorrow).
I'm not quite sure if my argumentation is right so feel free to ignore this until I opend the PR for output management.
The difference this PR makes is that now we can listen to `wlr_output_layout.change` and whenever this change is the addition of an output we now can be sure that the output is a fully initialized member of `Root.outputs`.
Currently the output is added to `Root.outputs` only after it is added to the `wlr_output_layout` which makes it hard for me to iterate over all outputs.
While typing I this noticed that I could also iterate over `wlr_output_layout.outputs`. But this feels wrong to me.
Also this introduces some some duplication of the call to …

code: Move wlr_output_layout_add from Output.init to Root.addOutput

---

contrib/config.sh
doc/riverctl.1.scd
river/command.zig
river/command/set_repeat.zig

This adds a 'set-repeat' command which sets the repeat rate and delay.
Most of the code is copied from River itself (not Sway this time), but one day I promise I'm going to make something without coping code.
Closes #70

Repeat Rate Command

---

river/Output.zig
river/OutputManager.zig
river/Root.zig
river/Server.zig
river/View.zig
river/c.zig
river/render.zig

Things that are still left to do
I hope to have time the ~next days~ ~weekend~ to finish the implementation.
When this is ready do NOT test with alacritty. Their scaling is bugged somewhere.

Implement wlr_output_management_unstable_v1

---

doc/riverctl.1.scd
river/Cursor.zig
river/Seat.zig

I think this is the expected behavior. I added a note in the man page to make it clear.
Also I simplified the code.

focus-follow-cursor: Change output focus when needed

---

build.zig
river/main.zig

Instead of hardcoding `/etc/river/init`, the config file will now be installed to `{b.install_prefix}/etc/river/init`. The path is passed to the river executable via `river.addBuildOption()`

build: fix #179 - add `default_config_path` build option

---

build.zig
example/options.zig
protocol/river-options-unstable-v1.xml
river/Option.zig
river/OptionsManager.zig
river/Server.zig

The idea with this protocol is to expose a key value store allowing clients to set and retrieve arbitrary configuration options as well as watch for changes in options. This would provide a simple mechanism to configure layout generators in an extensible way.
It is also planned to move any of river's simpler configuration options such as border width or background color over to this 
protocol.
TODO: 
- figure out how to implement output/seat specific options and if we really want them.
See also this discussion on IRC: https://freenode.irclog.whitequark.org/river/2021-01-14#1610623485-1610638349;
cc @Leon-Plickat

river-options: create protocol

---

build.zig
doc/riverctl.1.scd
riverctl/args.zig
riverctl/main.zig
riverctl/options.zig

To make this cleaner, introduce some arg-parsing infrastructure that
will useful when porting riverctl to river-control-v2 in the future as
well.

riverctl: implement river-options interface

---

river/command/swap.zig

Always using `.forward` results in a crash when running `swap previous` on the first view in stack which should be wrapped.
Stack trace from gdb before this fix when trying to `swap previous`:
```
attempt to use null value
/home/alex/repos/river/river/command/swap.zig:66:55: 0x21b435 in command.swap.swap (river)
if (it.next()) |next| next else it_wrap.next().?,
^
/home/alex/repos/river/river/command.zig:125:16: 0x24cd7d in command.run (river)
try impl_fn(allocator, seat, args, out);
^
/home/alex/repos/river/river/Control.zig:101:24: 0x239666 in Control.handleRequest (river)
command.run(util.gpa, seat, args, &out) catch |err| {
^
/home/alex/repos/river/zig-cache/zig-wayland/common.zig:101:76: 0x24d8f1 in .wayland.common.Dispatcher(.wayland.zriver_control_v1_server.ControlV1,*Control).dispat …
```

swap: use correct direction for it_wrap

---

river/Output.zig

Should fix #245
**TODO:** What to do when the margins are larger than the bounds? **A:** Just close the surface for now.

Layer shell fix

---

example/init

A typo in the init file uses `I` instead of `L` to increase the size of main_factor and main_count. This PR changes the occurances of `I` back to `L`.
Based on git history and the comments in example/init (and the behaviour of dwm), I am assuming `L` is the intended key.

example/init: Fix typos in introductory comment and keybindings

---

river/Cursor.zig
river/render.zig

This is a bit of an experiment, I'm not sure if I prefer this behavior in all cases yet but it does significantly help UX in some situations IMO (e.g. file dialogs and other such popups).

river: always render floating views above layout views

---

river/Seat.zig

This patch makes it possible to use the pointer to focus views on an unfocused output.
TODO: Clicking on an empty desktop should also change focus.

Allow changing output focus with pointer

---

river/LayerSurface.zig
river/Output.zig
river/Root.zig
river/Subsurface.zig
river/View.zig
river/XdgPopup.zig
river/XdgToplevel.zig
river/XwaylandUnmanaged.zig
river/XwaylandView.zig
river/render.zig

render: do basic yes/no damage tracking

---

.github/workflows/ci_build.yml

Zig relies on the existence of a system c compiler in order to
find the native libc include paths.

ci: add gcc to fix build

---

completions/zsh/_riverctl

Cleanup a bit too
Feel like the script is a little hacky, but as far as I understand `_arguments` only works with args like `-c |--commands` so I need to use `_alternative`, a bit redundant

completions/zsh: add input commands

---

river/XdgToplevel.zig

Ignore move and resize requests from fullscreended XDG toplevels.

---

river/InputManager.zig
river/LayerSurface.zig
river/Output.zig
river/Root.zig

A client is free to change its mind and request a different
size/anchor/etc after recieving the initial configure but before
attaching and committing the first buffer. This means that we should
respond to such a situation with a new configure.
mako has been observed doing this in the wild for example.
closes #226

layer-shell: handle commits before map

---

completions/bash/riverctl

Hello,
I noticed a typo in the bash completions while configuring river.
Thank you for the compositor!

completions: typo

---

doc/riverctl.1.scd
example/init
river/command/spawn.zig

Currently the spawn command takes any number of arguments and naively
joins them together with spaces before passing them as the single
argument of `/bin/sh -c`. This however produces unexpected results as
soon as shell quoting gets involved in the arguments passed to spawn.
For example, running
riverctl spawn foo "bar baz"
will execute `/bin/sh -c "foo bar baz"`, unexpectedly splitting bar and
baz into separate arguments. To avoid this confusion, make the spawn
command take only a single argument, forcing the user to quote properly
to spawn multi-argument commands.

river: make spawn command take only one argument

---

doc/rivertile.1.scd

Basically, renames the duplicated `main-count` to the correct `main-ratio`, according to the command's description.

Fix typo in rivertile doc/manual

---

build.zig

- Install river-layout-v3 in `$prefix/share/river-protocols/`
- Create `river-protocols.pc` in `zig-cache/` and install it in `$prefix/share/pkgconfig/`
Now for example in a 3rd party program you could use:
```zig
const std = @import("std");
const Builder = @import("std").build.Builder;
const ScanProtocolsStep = @import("deps/zig-wayland/build.zig").ScanProtocolsStep;
pub fn build(b: *Builder) !void {
[...]
const protocol_path = std.mem.trim(u8, b.exec(
&[_][]const u8{ "pkg-config", "--variable=pkgdatadir", "river-protocols" },
) catch unreachable, &std.ascii.spaces);
const layout_protocol = try std.fs.path.join(b.allocator, &[_][]const u8{protocol_path, "river-layout-v3.xml"});
scanner.addProtocolPath(layout_protocol);
[...]
}
```
I'm not sure about the version @ifreund, so tell me if …

build: Use pkg-config to handle river protocols

---

river/render.zig

Menus, tooltips, etc. can extend beyond a view's borders.  Render views after their borders so floating content appears on top.
Unfocused floating content can still be obscured by views higher in the stack and the focused view.
Fixes #382.

render: draw borders before rendering views

---

doc/riverctl.1.scd
river/Config.zig
river/XdgToplevel.zig
river/XwaylandView.zig
river/command/filter.zig

This extends the float-filter-add command using a 'prefix:string_to_match' syntax. The following prefixes are supported:
* `title`, which matches window titles
* `app-id`, which matches app ids
If no prefix is given, then `app-id` is assumed for backwards compatibility.
As an example following configuration floats all windows with the title 'asdf with spaces'.
riverctl float-filter-add 'title:asdf with spaces'
The syntax was briefly discussed in #289. As I understand Leon, this is intended as a small quality-of-life change for existing setups. This implementation only checks view titles on creation, not upon title changes. I wouldn't know of a usecase for the latter, so I'd say we don't implement it.
Feedback wanted :) I'm new to both wayland and zig, so don't hold back!

Allow float-filter-add to inspect window titles

---

doc/riverctl.1.scd
example/init
river/Config.zig
river/Decoration.zig
river/XdgToplevel.zig
river/command/filter.zig

This extends the `csd-filter-add` command to allow matching on window
titles as well, using a `csd-filter-add kind pattern` syntax. The
following kinds are supported:
* `title`, which matches window titles
* `app-id`, which matches app ids
Only exact matches are considered.
As an example following configuration applies client-side decorations to
all windows with the title 'asdf with spaces'.
riverctl csd-filter-add title 'asdf with spaces'
----
This commit makes the `*-filter-add` consistent over floats and csds.

river: Allow applying CSD based on window titles

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl
doc/riverctl.1.scd
river/command.zig
river/command/tags.zig

Closes https://github.com/ifreund/river/issues/416. This isn't just for symmetry's sake, as I find that `send-to-previous-tags` really does complement `focus-previous-tags` well. `focus-previous-tags` is great because it allows you to temporarily replace the mental overhead of alternating between tags like "$mod+1, $mod+7, $mod+1..." with one repeated keystroke, but if you want to send a view to the alternate tagset you have to break out of that shortcut and recall which tags you were using. My typical use case is starting a couple of related, slow to start applications, e.g. an IDE and a SQL client, or Steam and a game, in my working tagset and sending them to the alternate tagset at they pop up.
Would it be worth adding default bindings for this and `focus-previous-tags` in the example …

river: add send-to-previous-tags command

---

README.md

The GitHub repo is archived and redirects to [https://gitlab.freedesktop.org/wlroots/wlroots](https://gitlab.freedesktop.org/wlroots/wlroots)

fix wlroots link in README.md

---

contrib/river.desktop

I recently made a river Debian package and included a desktop file to be installed in /usr/share/wayland-sessions. I noticed that the river-git AUR package does the same thing, So, to avoid duplicating work and to keep things consistent between distributions, I thought it would be worthwhile if upstream river shipped with a desktop file that all packagers could make use of. This desktop file in this branch is almost identical to the one from AUR river-git differing only in the capitalization for "River" and in the addition of a newline at the end of the file.

contrib: add desktop file

---

rivertile/main.zig

As far as I could tell this is the only occurrence where we can replace it. Grepping around, the only other case of `maxInt(T)` are use to set a value. Grepping for `math` also doesn't return any `math.mul/add/...`

rivertile: Use saturating addtion

---

doc/riverctl.1.scd
river/InputManager.zig

A conversation on IRC showed me that device names aren't so unique after all and that multiple devices with the exact same name can be encountered in the real world.
Currently, river will apply an output config to the first input device with a matching device name. Input devices sharing the same name will not get the configuration because the loop `break`'s, which this patch changes.
Maybe we can instead make the names more unique. This however needs to be implemented in a way so that device names still stay consistent between sessions, so for example we can not just prefix them with a counter. Perhaps we can prefix them with the device type (like `touchpad:000:000:company-touchpad-something`), but that would still break if there are multiple devices with the same name of the same type. …

Don't stop applying input configs after first match.

---

river/Config.zig
river/Mode.zig
river/command/declare_mode.zig
river/command/map.zig

- Use ArrayListUnmanaged for `Mode.mappings` and `Mode.pointer_mappings` and also for `Config.Mode`.
- Remove `Mode.init()` as the array list can be directly initialized in `Config.init()`, could be added back if any objection. But imo unless I missed something this doesn't seems to be really useful:
``` zig 
pub fn init() Self {
return .{
.mappings = .{},
.pointer_mappings = .{},
};
}
```

Mode: Use ArrayListUnmanaged to save memory

---

build.zig
river/Cursor.zig
river/Decoration.zig
river/InputManager.zig
river/Layout.zig
river/LayoutDemand.zig
river/Root.zig
river/Seat.zig
river/Server.zig
river/XdgToplevel.zig
river/command.zig
river/command/attach_mode.zig
river/command/config.zig
river/command/input.zig
river/command/layout.zig
river/command/map.zig
river/command/move.zig
river/command/output.zig
river/command/spawn.zig
river/command/tags.zig
river/main.zig
river/render.zig
river/util.zig
riverctl/main.zig
rivertile/main.zig

So I come accross some case where there was in the same file for example `std.mem.foo()` but also `const mem = std.mem;` at the beginning of the file, so I tried to cleanup a bit everything, either adding `const foo = std.foo` if the lib was called a lot of time or just fix when both `std.foo` and `foo()` were used.
Sorry for the not so great commit message, I didn't know how to describe this tbh.

code: Cleanup use of std library for consistancy

---

river/Root.zig
river/View.zig
river/XdgToplevel.zig
river/XwaylandView.zig

I have encountered a crash (failing assert) if a view specified a fixed
size less than this minimum, and according to ifreund this behavior was
planned to be removed, anyway.

view: stop enforcing custom minimum size

---

doc/river.1.scd

The river man page lists the log levels as "error|warn|info|debug", but level "warn" doesn't exist. The correct level, as `river --help` shows, is "warning".
I bypassed setting up an issue since this is basically a typo. If this was a bad idea, I sincerely apologize.

river-man-page: change log level warn to warning

---

doc/riverctl.1.scd
river/Config.zig
river/Cursor.zig
river/Keyboard.zig
river/command.zig
river/command/cursor.zig

From the riverctl.1:
```
*hide-cursor* *timeout* _timeout_
Hide the cursor if it wasn't moved in the last _timeout_ milliseconds, until
it is moved again.
The default value is 0, which disables automatically hiding the cursor.
*hide-cursor* *jitter* _hide_delta_ _unhide_delta_
- _hide_delta_: How many logical pixels the cursor has to move to reset the
hide timeout.
- _unhide_delta_: How many logical pixels the cursor has to move to show the
cursor again.
The default value is for both is 0, which disables the jitter.
*hide-cursor* *jitter* _delta_
Sets both *hide-cursor* *jitter* _hide_delta_ and _unhide_delta_ to _delta_.
*hide-cursor* *when-typing* *enabled*|*disabled*
Hide the cursor when typing starts, the cursor has to move to be shown again.
```

Add command to hide cursor while typing or after a timeout

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl

Add shell completions (for bash/zsh/fish) for the `hide-cursor` command.

Shell completions for 'hide-cursor' riverctl command

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl
doc/riverctl.1.scd
river/Keyboard.zig
river/Mapping.zig
river/Seat.zig
river/command/map.zig

After some discussions, we came to the conclusion, that layout-independent mappings are best achieved with the ability to pin a certain layout to a mapping.
E.g. something like `riverctl map -layout "French" normal Super Y spawn foot`.
When this mapping is checked, the specified layout will be used to translate the received key instead of the currently active layout.
The details are yet to be decided.

layout-independent mappings

---

river/command/input.zig

Run the following commands to see where the typo appears:
```bash
riverctl input my_device natural-scroll enabled
riverctl list-input-configs
```

Fix typo in natural-scroll

---

river/IdleInhibitor.zig
river/IdleInhibitorManager.zig
river/Root.zig
river/Server.zig
river/View.zig

Implementation of the idle inhibit protocol. Closes https://github.com/riverwm/river/issues/199
Depends on https://github.com/swaywm/zig-wlroots/pull/43

Implement Idle Inhibit Protocol

---

river/Cursor.zig
river/Seat.zig
river/XwaylandUnmanaged.zig

This should resolve https://github.com/riverwm/river/issues/455 by adding keyboard focus on map for unmanaged Xwayland views that want it (based on the relevant TODO, using wlroot's heuristic). It also adds keyboard focus when clicking on an unmanaged Xwayland view, for some consistency with layer surfaces. This was initially based on the closed PR https://github.com/riverwm/river/pull/569.
I have tested this with dmenu, as in the linked issue, and polybar (at top and bottom of screen), and it works on my end. However, there is a problem: I am unable to select an unmanaged Xwayland surface if I have another view in fullscreen. This appears to be an issue with `surfaceAt()` failing in `xwaylandUnmanagedSurfaceAt()` when in fullscreen, but I am not sure.

xwayland-unmanaged: handle focus on map/cursor button

---

river/XwaylandUnmanaged.zig
river/XwaylandView.zig

Handling of the `set_override_redirect` listener in `create()` and `handleDestroy()` was missed in https://github.com/riverwm/river/commit/6ef97eea241ecc5bec32e0cf820c3644692f5554, so Xwayland views don't actually switch between being managed and unmanaged.

Xwayland: add handling of override redirect listeners

---

river/Keyboard.zig
river/KeycodeSet.zig
river/Seat.zig

For a normal (on press) mapping, do not send the press and release events and remove the key from `wl_keyboard::enter`. For a `-release`-only mapping, send the key to the client as if nothing was mapped.
Fixes #444
Draft status because cleanup (removing debug logs, TODO/FIXME) is still needed. Functionality-wise, the PR is done.

Eat mapped keys

---

build.zig
protocol/river-status-unstable-v1.xml
river/Config.zig
river/InputManager.zig
river/Mode.zig
river/Seat.zig
river/SeatStatus.zig
river/StatusManager.zig
river/command/declare_mode.zig
river/command/enter_mode.zig

This allows clients such as a status bar to display the currently active
mode.

river-status: add mode event to seat status

---

river/main.zig

since it's such a common mistake.

Abort if default init is not executable

---

.builds/archlinux.yml
.builds/freebsd.yml
.github/workflows/ci_build.yml

This is currently pulled in transitively on void, arch, and FreeBSD
which just stopped working on void due to upstream changes.

ci: explicitly install libevdev

---

river/LayoutDemand.zig

The condition was wrong for the first extra view (0 isn't < 0), plus
the counting stopped at that moment.

LayoutDemand: handle too many view dimensions correctly

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl
doc/riverctl.1.scd
river/InputDevice.zig
river/Keyboard.zig
river/KeyboardGroup.zig
river/Seat.zig
river/command.zig
river/command/keyboard_group.zig

Usage:
```
riverctl keyboard-group-create <group-name>
riverctl keyboard-group-add-keyboard <group-name> <input-device-identifier>
```
Still a few rough spots, but it works.

river: implement keyboard groups

---

build.zig
doc/riverctl.1.scd
river/Cursor.zig
river/DragIcon.zig
river/InputManager.zig
river/LayerSurface.zig
river/LockManager.zig
river/LockSurface.zig
river/Output.zig
river/Root.zig
river/Seat.zig
river/Server.zig
river/Subsurface.zig
river/XdgPopup.zig
river/XdgToplevel.zig
river/XwaylandOverrideRedirect.zig
river/XwaylandView.zig
river/command/config.zig
river/render.zig

Since river tracks the latest wlroots releases, I've cherry-picked the wlroots commit linked above onto the 0.15.0 tag for testing. Branch here: https://gitlab.freedesktop.org/ifreund/wlroots/-/tree/session-lock-0.15
This can be tested with the swaylock implementation of this protocol here: https://github.com/swaywm/swaylock/pull/219

ext-session-lock: implement protocol

---

protocol/river-status-unstable-v1.xml
river/Layout.zig
river/Output.zig
river/OutputStatus.zig

We've had the layout name forever and never actually send it forward to status clients.

river-status: add layout_name and layout_name_clear events

---

protocol/river-status-unstable-v1.xml

Noticed a typo in a recent commit.
whent -> when

river-status: fix typo in layout_name_clear description

---

river/Server.zig

Depends on swaywm/zig-wlroots/pull/59.

support single_pixel_buffer_v1 protocol

---

river/command/move.zig

In 489a49735 the view.move() call, which is used to keep the view centered after a resize, was accidentally removed.

river: fix resize command

---

river/Cursor.zig
river/LockManager.zig
river/Output.zig
river/Seat.zig
river/render.zig

Currently the session lock client has no 100% safe way to know when it is safe to suspend after requesting that the session be locked.
For a suspend to be safe the compositor must have either blanked or rendered a lock surface on all outputs before suspending. This is because the current framebuffer on suspend appears to be saved and displayed again after suspend, at least on my Linux system.
If a new "locked" frame for all outputs is not rendered before suspend, an "unlocked" frame or frames will likely be briefly displayed on resume before the lock surfaces are rendered or the screen is blanked.
To fix this, wait until a lock surface has been rendered on all outputs, or if that times out until all outputs have been blanked, before sending the locked event to the client.
Resolving this …

session-lock: fix potential race

---

river/Cursor.zig
river/DragIcon.zig
river/Root.zig
river/Seat.zig
river/render.zig

Closes #634
Any help testing this PR by people with touchscreens would be much appreciated and is require before this can be merged as I don't have a test system with a touch screen currently.
To test, the `weston-dnd` client might be useful. Alternatively, dragging firefox tabs by touch should work now in theory and show a drag icon just as dragging them with the pointer currently does.

touch: support drag and drop

---

protocol/river-control-unstable-v1.xml
river/Control.zig

I suppose these kind of changes require a version bump, but since callback has no requests, this change should not break anything. Please let me know if my assumption is wrong.

river_control: mark callback events as destructors

---

river/command/move.zig

Found a bug in snap down / snap right. The calculation of view.pending.box is inverted:
- snap right should use output_width (not output_height)
- snap down should use output_height (not output_width)

river: fix bug in snap down / right

---

.builds/alpine.yml
.builds/archlinux.yml
.builds/freebsd.yml

Using `meson build` without `setup` have been deprecated, fix warning message:
'WARNING: Running the setup command as `meson [options]` instead of
`meson setup [options]` is ambiguous and deprecated.

ci: Use meson setup command

---

river/Cursor.zig
river/Seat.zig
river/XwaylandOverrideRedirect.zig
river/XwaylandView.zig

I have looked into https://github.com/riverwm/river/issues/620 again and more deeply, and I believe I have found a final solution. I feel, however, that it can be improved because it is not in keeping with river's normal behaviour. Specifically, two views can be activated at the same time: If an Xwayland override redirect surface takes focus and a normal view was in focus previously, the previous view's focus will *not* be removed; the focus for this view is only reset if a new view takes focus over the override redirect surface. This ensures that when an Xwayland popup menu (or similar) is created, its parent Xwayland view is still activated, allowing the menu to continue its operation. (Perhaps deactivating the parent view implies that the view's popup menu should no longer be shown?) …

Xwayland: keep previous view activated when focusing Xwayland OR surfaces

---

river/View.zig

This cause `seat_node.data.focused.view == &self` to be false and so to never send the focused view title to client
Fixed #771

View: Fix self pointer in notifyTitle()

---

river/Root.zig

Apply changes to adaptive sync from wlr-output-management clients.
See similar sway PR: https://github.com/swaywm/sway/pull/7395
Test cases with [way-displays](https://github.com/alex-courtis/way-displays) 1.7.1:
supported display:
```
I [13:26:23] DP-1 Changing:
I [13:26:23]   from:
I [13:26:23]     scale:    1.000
I [13:26:23]     position: 0,0
I [13:26:23]     mode:     3840x2160@144Hz (144,000mHz)
I [13:26:23]     VRR:      off
I [13:26:23]   to:
I [13:26:23]     VRR:      on
I [13:26:23]
I [13:26:23] Changes successful
```
unsupported display:
```
I [13:40:30] eDP-1 Changing:
I [13:40:30]   from:
I [13:40:30]     scale:    1.000
I [13:40:30]     position: 0,0
I [13:40:30]     mode:     2560x1440@60Hz (59,998mHz) (preferred)
I [13:40:30]     VRR:      off
I [13:40:30]   to:
I …
```

Apply new adaptive sync value from wlr-output-management

---

doc/riverctl.1.scd
river/command/output.zig

As proposed on IRC, this implements the option to pass `-current-tags` to the `send-to-output` command. The flag will cause views to be tagged with the views of the destination when send to a different output. 
Visually, this results in the view always staying visible on output move.

Implement -current-tags for send-to-output

---

.editorconfig

https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#charset seems to suggest that the value should be named `utf-8` and Neovim with `editorconfig` enabled complained for me as-is.

editorconfig: fix typo

---

river/XdgToplevel.zig

When a floating window resizes itself, the new size won't automatically end up in wlroots' XdgToplevel.scheduled, so river needs to always set the size when configuring a toplevel.
This makes `weston-fullscreen` no longer jump back to its old size when resized after pressing `z`.

Respect resizes coming from clients

---

riverctl/main.zig

Adds error messages for when the connection to the server fails. The case of people trying to use riverctl in a TTY without knowing that it needs `WAYLAND_DISPLAY` seems common enough and I think proper error messages will help a bit here.

riverctl: Add error messages for failed connections

---

river/command/rule.zig

river: fix crash when trying to add tag rule without tag argument

---

completions/zsh/_riverctl

- Fix some completions that never really worked correctly, e.g `riverctl input` didn't take the input name into account. Same with rule that didn't take into account glob.
- Add a lot of documentation to help people adding new commands.
- Add new rule-[add|del] order.
- `riverctl input` now autocomplete input name from `riverctl list-inputs`
This is still not perfect but it"s an improvement and I hope it can remove a bit of confusion when there is a need to add a new commands.

completions: Rewrite zsh

---

completions/zsh/_riverctl

Input name with ':' in it were not suggested entirely.
Sorry I didn't catch this earlier, `_values` wasn't working exactly how I thought. It seems to be fine now.
But if anyone still got any problems I will just remove it and use an empty args like for `glob` in `rule-[add|del]`.

completions/zsh: Fix incomplete input names

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl
doc/riverctl.1.scd
river/Config.zig
river/View.zig
river/command/rule.zig

This commit adds position and dimensions rules for configuring
the initial position and dimensions of views.
When a view is not matched by any position rules, it is centered
in the avaliable output space matching the current behavior. If
the provided position rule places the view outside of the output,
the view's position is clamped to the output bounds (with respect
to borders).
When a view is not matched by any dimensions rules, no default
dimensions is set by the server. If the provided dimensions rule
exceeds the minimum or maximum width/height constraints of the view,
the view's width/height is clamped to the constraints.
partially implements https://github.com/riverwm/river/issues/865
I am relatively new to Zig and Wayland, please let me know if I am doing anything incorrectly. I …

river: add position, dimension and fullscreen rules

---

river/InputManager.zig
river/InputRelay.zig
river/Keyboard.zig
river/KeycodeSet.zig
river/Seat.zig
river/TextInput.zig

adapted from #405. the keyboard logic could possibly be done in a cleaner way, but it's currently working for me.
the keyboard grab eats keycodes in a similar way as the user-defined mappings. because the grab has to handle releases of grabbed presses it checks releases for membership in the eaten keycode set, and ungrabs if the presses weren't eaten.

river: Implement input_method and text_input

---

river/Server.zig

This code could allows the view to be focused and urgent at the same time if the request to activate the view is received just after the pending focus has been set but before the transaction completes.
Hopefully fixes #941, needs testing by someone who can reproduce that issue.

xdg-activation: fix race with transaction system

---

build.zig
river/Cursor.zig
river/Output.zig
river/Server.zig

Also set `xcursor_name` field of the `Cursor`. Currently it is always `null`.
I've put `handleRequestSetCursorShape` in `Server.zig` because that's where the manager is created. I should probably move it to `Cursor.zig`?
Closes #932

Implement cursor_shape_v1

---

river/Cursor.zig

Cursor: When `focus-follows-cursor` is set and the cursor moves onto an output where no views are present on the currently visible tags, focus the output itself instead of an individual view.
This is useful e.g. when you want to spawn a terminal on your empty monitor or switch it to a different tag.  Previously such changes would happen to the monitor on which you previous focus was, despite the cursor being somewhere else.

Focus follows cursor focuses empty outputs

---

doc/riverctl.1.scd
river/Keyboard.zig
river/KeyboardGroup.zig
river/command/keyboard_group.zig

Use globber for matching identifiers in keyboard groups.
Real-world use cases:
* A physical keyboard exposes multiple virtual keyboards with similar but not exactly equal names. Using globs simplifies the configuration *a lot* in this case.
* A user wants to have all keyboards in a group, possible with the `*` glob.
Depends on #949

Keyboard group glob

---

river/InputConfig.zig

river: fix names of input config settings

---

doc/riverctl.1.scd
river/InputConfig.zig
river/InputDevice.zig
river/InputManager.zig
river/command/input.zig

use globs for input config

---

river/main.zig

This clarifies that the `-c` parameter overrides the default init executable and isn't run in addition to it in the `--help` dialog.

Improve documentation for -c parameter in --help message

---

completions/bash/riverctl
completions/fish/riverctl.fish
completions/zsh/_riverctl
doc/riverctl.1.scd
river/InputConfig.zig
river/InputManager.zig
river/Root.zig
river/command/input.zig

This adds support for a `input X map-to-output Y` command.
closes #635

command/input: add map-to-output

---

example/init

Change screen backlight brightness command to brightnessctl(1) as light(1) repo has been deleted.
closes #1008

example/init: Replace light with brightnessctl

---

river/Root.zig
river/View.zig
river/command/output.zig

implements #666 
untested, will test tomorrow when I am back at my desk.
(should have waited for #999 to be the next number, but oh well)

restore views to evacuated outputs on reconnect

---

river/TabletTool.zig

Use "pencil" cursor shape instead of "default" for tablet tool devices.

river: use "pencil" cursor shape for TabletTool
