- doc/riverctl.1.scd
- river/Output.zig
- river/View.zig
- river/command.zig
- river/command/attach_mode.zig
- river/view_stack.zig
Solves #90 
More modes (like "below focus" or "above focus") can be easily added in a future commit.
> Implement "attach-mode"

- doc/riverctl.1.scd
I messed up the formatting in my last pr.
> docs: focus-follows-cursor fix options to be bold

- river/Seat.zig
- river/Server.zig
- river/c.zig
Implements all three types of primary selection.
> Implement primary selection

- doc/riverctl.1.scd
- river/Config.zig
- river/InputManager.zig
- river/Seat.zig
- river/command/enter_mode.zig
> Introduce mode "locked"

- river/View.zig
- river/XdgToplevel.zig
- river/XwaylandUnmanaged.zig
- river/XwaylandView.zig
This makes XwaylandView.zig more like XdgToplevel.zig mostly in the "making windows float" area, which fixes an issue I was having with Kicad where if you open the 'Edit Value' window a second time, Kicad would freeze.
> Make XwaylandView.zig a little more like XdgToplevel.zig

- doc/riverctl.1.scd
- river/command.zig
- river/command/swap.zig
- river/view_stack.zig
The `importance` command simply swaps the focused node with the node above/below in the view stack.
I am open to other name suggestions.
I introduced a rather complicated looking `ViewStack.swap` function.
I'm not sure if this is good or not since it is only used in one place.
What are your thought about this?
----
Addresses one part of #12
> Introduce importance command

- river/XdgToplevel.zig
- river/XwaylandView.zig
> Send zriver_seat_status_v1.focused_view when title of focused view changes

- doc/riverctl.1.scd
- river/command.zig
- river/command/map.zig
Edit:
I thought this was discussed somewhere but I can't remember where.
An obvious usecase is remapping keys in a running session.
> Implement unmap and unmap-pointer

- river/InputManager.zig
- river/c.zig
See https://github.com/ifreund/river/pull/138
> Implement wlr_virtual_pointer_unstable_v1 protocol

- build.zig
Related: https://github.com/ifreund/zig-wayland/pull/10
> code: Replace deprecated std.fmt.trim with std.mem.trim

- river/main.zig
As discussed in #147.
With this patch, if a config path is not provided by user, river tries `$XDG_CONFIG_HOME/river/init` and `/etc/river/init`.
> Add default config location

- river/main.zig
As discussed in #154
Closes #154
> code: Set wlroots loglevel based on -l flag

- .github/workflows/ci_build.yml
- river/main.zig
> ci: clone submodules, cleanup

- contrib/config.sh
- doc/river-layouts.7.scd
- doc/river.1.scd
- doc/riverctl.1.scd
- doc/rivertile.1.scd
Basically just run vims `gq` on every paragraph, unified the styles and removed outdated information.
> Cleanup man pages and `contrib/config.sh`

- build.zig
- river/Cursor.zig
Depends on https://github.com/swaywm/zig-wlroots/pull/10
Pinching can be tested with evince and swiping can be tested with the GNOME Web.
> Implement pointer_gestures_v1

- AUTHORS
- build.zig
- river/Cursor.zig
- river/InputManager.zig
- river/PointerConstraint.zig
- river/Seat.zig
This time I did not copy Sway's code, but instead I read Sway's code to get an idea of what I should do or see how Sway solves a problem, closed Sway's code, and then wrote my own code.
Pointer constraints can be tested with the wlroots pointer constraints example.
Relative pointer can be tested with Minetest.
> Pointer Constraints and Relative Pointer

- build.zig
- completions/zsh/_riverctl
I think I didn't forget any command, it works for all commands and some sub-commands for when there is a choice like `next previous`
> completions: add zsh completion for riverctl

- build.zig
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
Rip off from the previous commit for zsh completion :)
I also fixed some typos.
> Add riverctl completion for fish shell

- river/render.zig
This should fix rendering "freezes" reported in #153
Tested on FreeBSD 14-current
> Fix #153 (screen freezing issues)

- README.md
Just add a link to repology.org in the README.md, I think it's all we need
> README: add repology badge

- river/PointerConstraint.zig
I think it was just that, at least it build without error so
> river: fix to work with latest zig-pixman

- contrib/layout.c
> contrib: Update layout.c for river-layout-v2

- doc/rivertile.1.scd
send-layout-value → set-layout-value
> doc: fixed command name in example

- rivertile/main.zig
> rivertile: clamp main_amount

- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/Config.zig
- river/Output.zig
- river/View.zig
- river/command/attach_mode.zig
I don't have multi output to try it
Closes #269
> config: make attach-mode global

- completions/fish/riverctl.fish
I can't find a way to use switch case, so I resolved to use 3 "same" functions.
> completions: add fish completion for input command

- README.md
Just a small PR to add a link to the FAQ and recommended software in the README to perhaps have more people reading it
> README: add a link to the wiki

- river/Cursor.zig
- river/Root.zig
- river/util.zig
~~Not sure if this is the right approach.~~ It works, so it'll be fine.
> Reset cursor state on output or tag focus change

- completions/bash/riverctl
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/Keyboard.zig
- river/Mapping.zig
- river/Seat.zig
- river/command.zig
- river/command/map.zig
This implements #306.
I'm new to both Zig and Wayland and welcome any feeback on style or approach.
> Add repeating keyboard mappings

- completions/bash/riverctl
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- protocol/river-status-unstable-v1.xml
- river/Config.zig
- river/Output.zig
- river/OutputStatus.zig
- river/Root.zig
- river/Seat.zig
- river/Server.zig
- river/StatusManager.zig
- river/View.zig
- river/XdgToplevel.zig
- river/command.zig
- river/command/config.zig
- river/render.zig
Currently doesn't do anything with urgent views since we need to discuss what to do
I updated zig-wlroots to the latest commit, maybe @ifreund you prefer just to the commit that add xdg_activation_v1 binds?
> Implement xdg_activation_v1

- river/command/filter.zig
This snuck by during the review of #415
> river: Fix errdefer in floatFilterAdd

- river/command.zig
The `// TODO` told me to do it.
Looks cleaner, but for the low amount of strings the performance improvement is probably not measurable.
> command: Use std.ComptimeStringMap to get impl. function from command string

- completions/fish/riverctl.fish
We can all agree that the 1st function looks really ugly :)
So I made it more simple to read.
> completions/fish: simplify

- river/Output.zig
> layer-shell: tighten up handling of large margins

- river/Cursor.zig
This patch allows to focus outputs by clicking on the empty background and by
clicking on layer surfaces without keyboard interactivity. This makes it
possible to use the cursor to focus outputs with no visible views.
This also fixes problems with pointer interactive layer surfaces (for example
launchers and docks) on non-focused outputs.
> improve cursor output focusing on button press

- .github/workflows/ci_build.yml
- README.md
- river/Cursor.zig
- river/InputManager.zig
- river/LayerSurface.zig
- river/Layout.zig
- river/LayoutDemand.zig
- river/LayoutManager.zig
- river/Output.zig
- river/Root.zig
- river/Server.zig
- river/Subsurface.zig
- river/XdgToplevel.zig
- river/command/input.zig
- river/render.zig
let's let the CI run before I push this to master.
> river: update to wlroots 0.15.0

- river/command/map.zig
Just display a message warning the users, don't throw errors and still map the new keybinding.
closes #482
> command/map: Warn users on keybinding overwritten

- river/Switch.zig
river crashes on exit without this.
> Switch: register destroy listener

- river/Mapping.zig
When checking keys for matching mappings, previously we did two checks:
1. Keysyms translated by xkb.
2. Raw keysyms
This commit removes the first check, so only the second is checked.
As discussed in #604
> mappings: Do not translate keys with xkb

- river/Output.zig
In cases like multiple hi-res monitors connected through a USB dock, the
preferred mode can fail to work. Such an output was then ignored by river,
which made it impossible to even set another mode manually.
Sway has been reported to solve this issue, so let's employ their solution
and fall back to another mode if possible.
Likely fixes #502.
> Output: retry other modes if preferred fails

- river/main.zig
When river or wlroots write to a closed socket it could generate SIGPIPE causing the whole desktop to seemingly "crash" with no error log of any kind. So ignore the SIGPIPE and let write fail with EPIPE.
> river: block SIGPIPE on start to avoid weird exits

- river/View.zig
There is still a problem with floating fullscreen views.
> river: keep view within bounds when sending to output

- river/LayoutManager.zig
> river: advertise correct version of layout protocol

- completions/bash/riverctl
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/InputDevice.zig
- river/Keyboard.zig
- river/KeyboardGroup.zig
- river/Seat.zig
- river/command.zig
- river/command/keyboard_group.zig
This builds off of #687 and refactors some parts of the implementation in an attempt to reduce global complexity/dimensionality.
This seems to all work properly from my basic testing, though I don't have keyboards for which this feature is required.
cc @Leon-Plickat
> Alternative Keyboard group implementation

- contrib/layout.py
It took me a while to figure out how to activate this layout, adding a note to the Q&A.
Also correct typo.
> Add Q&A for how this layout is used

- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- example/init
- river/Cursor.zig
- river/Mode.zig
- river/PointerMapping.zig
- river/Seat.zig
- river/command/map.zig
resolves #685
superceeds #691
`map-pointer mode modifiers button action|command`
View under cursor is always focused when mapped button pressed.
> map-pointer command

- doc/riverctl.1.scd
- river/Config.zig
- river/Keyboard.zig
- river/command.zig
- river/command/keyboard.zig
> add command to set keybaord layout

- river/Cursor.zig
When focus-follows-cursor is used with cursor-warp, some windows will get focus before the cursor properly "enters" the window since they have a larger input-region than their window geometry, this causes the cursor to be yanked to the middle unexpectedly.
This fix makes it so the focus is only given when the cursor enters the window geometry.
> Rework focus-follows-cursor to work with warp

- river/Config.zig
- river/command/config.zig
> fix border color by premultiplying alpha

- river/command/view_operations.zig
> river: fix spatial direction focusing / swapping

- completions/bash/riverctl
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/Config.zig
- river/View.zig
- river/command/rule.zig
- river/rule_list.zig
This adds the ability to create rules that change the initial output of a view.
(Sorry if my code is not that great, I haven't used Zig a lot, feedback is welcome)
> Add output rule

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- README.md
- build.zig
- river/Cursor.zig
- river/DragIcon.zig
- river/IdleInhibitorManager.zig
- river/Keyboard.zig
- river/LayerSurface.zig
- river/LockManager.zig
- river/LockSurface.zig
- river/Output.zig
- river/Root.zig
- river/SceneNodeData.zig
- river/Seat.zig
- river/Server.zig
- river/XdgDecoration.zig
- river/XdgToplevel.zig
- river/XwaylandOverrideRedirect.zig
- river/XwaylandView.zig
- river/main.zig
Edit:
This branch seems to be nearly ready to merge.
I've hidden the comments I believe to be discussing outdated issues in order to make it easier to determine what is left to do before merging this branch. If I've made any errors there please let me know :)
> build: update to wlroots 0.17

- river/Server.zig
> river: Implement fractional_scale_v1

- doc/riverctl.1.scd
- river/Config.zig
- river/Output.zig
- river/View.zig
- river/command.zig
- river/command/attach_mode.zig
See: https://github.com/riverwm/river/issues/904
> river, rivertile: implement attach-mode aside.

- river/InputConfig.zig
- river/command/input.zig
Use meta-programming to make the input configuration mechanism a bit cleaner.
Also added a new debug log message which should help when debugging #959
> refactor input configuration

- completions/bash/riverctl
- completions/fish/riverctl.fish
- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/InputConfig.zig
New option in libinput https://wayland.freedesktop.org/libinput/doc/latest/configuration.html#disable-while-trackpointing
I don't have the hardware to test it though so if someone with a trackpoint can try it that would be nice.
> InputConfig: Implement disable while trackpointing

- completions/zsh/_riverctl
- doc/riverctl.1.scd
- river/Config.zig
- river/Output.zig
- river/View.zig
- river/command/attach_mode.zig
> command/attach-modes: above and below options

- river/Output.zig
- river/View.zig
Fixes the problem described in #1013.
> View: Add attachRelative function

- README.md
> README: update required wlroots version to 0.17.2

- doc/riverctl.1.scd
- river/command/view_operations.zig
> implement '-skip-floating' flag for 'focus-view'
